[[factories]]
== Getting Started with Factories

In this lab you will learn how to work with `factories` including:

. How to create factories
. How to invoke factories

NOTE: For this lab you should already have a functioning workspace.

=== What is a Factory?
A factory is a template containing configuration to automate the generation of a new workspace using a factory identifier added to the IDE URL. Factories can be used to create replicas of existing workspaces or to automate the provisioning of statically or dynamically defined workspaces.

Factory configurations are defined with JSON and strored within CodeReady Workspaces or as a `.factory.json`.

Example: 
```json
factory : {
  "v"         : 4.0, // Configuration format version.
  "workspace" : {}, // 
  "ide"       : {},
  "creator"   : {},
}
```

=== Creating Factories
Factories can be created within the IDE using the CodeReady Workspaces URL syntax, withing the dashboard, or on the command line with the API and CLI.




=== Invoking Factories
Factories can be instantiated or "invoked" by their unique hashcode, the factory name, or from a specific Git repository. Today we will be invoking a name factory for simplicity.

.Invoking a named factory
|===
|Format | `/factoryf?id={hashcode}``
|Sample | https://localhost:8080/factory?id=factorymtyoro1y0qt8tq2j
|==

 - Mixins
 - Devfile v. Factory